const Map<String, List<String>> usCitiesByState = {
  'Alabama': [
    'Abbeville', 'Adamsville', 'Alabaster', 'Albertville', 'Alexander City',
    'Aliceville', 'Anniston', 'Arab', 'Athens', 'Atmore', 'Attalla', 'Auburn',
    'Bay Minette', 'Bessemer', 'Birmingham', 'Boaz', 'Brewton',
    'Calera', 'Centre', 'Childersburg', 'Citronelle', 'Clanton',
    'Cullman', 'Daphne', 'Decatur', 'Demopolis', 'Dothan',
    'Enterprise', 'Eufaula', 'Fairhope', 'Fayette', 'Florence',
    'Foley', 'Fort Payne', 'Gadsden', 'Gardendale', 'Greenville',
    'Guntersville', 'Hamilton', 'Hartselle', 'Helena', 'Homewood',
    'Hoover', 'Huntsville', 'Jacksonville', 'Jasper',
    'Leeds', 'Lincoln', 'Linden', 'Madison', 'Marion',
    'Millbrook', 'Mobile', 'Monroeville', 'Montgomery', 'Moody',
    'Mountain Brook', 'Muscle Shoals', 'Northport', 'Oneonta',
    'Opelika', 'Orange Beach', 'Oxford', 'Ozark',
    'Pelham', 'Pell City', 'Phenix City', 'Prattville', 'Prichard',
    'Rainbow City', 'Roanoke', 'Russellville', 'Saraland',
    'Scottsboro', 'Selma', 'Sheffield', 'Sylacauga', 'Talladega',
    'Troy', 'Trussville', 'Tuscaloosa', 'Tuscumbia', 'Tuskegee',
    'Vestavia Hills', 'Wetumpka',
  ],
  'Alaska': [
    'Anchorage', 'Barrow', 'Bethel', 'Cordova', 'Craig',
    'Delta Junction', 'Dillingham', 'Eagle', 'Fairbanks',
    'Fort Yukon', 'Galena', 'Glennallen', 'Haines', 'Homer',
    'Hoonah', 'Houston', 'Juneau', 'Kenai', 'Ketchikan',
    'King Cove', 'Kodiak', 'Kotzebue', 'Metlakatla', 'Nome',
    'North Pole', 'Palmer', 'Petersburg', 'Sand Point',
    'Seward', 'Sitka', 'Skagway', 'Soldotna', 'Tok',
    'Unalaska', 'Valdez', 'Wasilla', 'Wrangell',
  ],
  'Arizona': [
    'Apache Junction', 'Avondale', 'Benson', 'Bisbee', 'Buckeye',
    'Bullhead City', 'Camp Verde', 'Casa Grande', 'Cave Creek', 'Chandler',
    'Chino Valley', 'Clifton', 'Coolidge', 'Cottonwood', 'Douglas',
    'El Mirage', 'Eloy', 'Flagstaff', 'Florence', 'Fountain Hills',
    'Gilbert', 'Glendale', 'Globe', 'Goodyear', 'Holbrook',
    'Kingman', 'Lake Havasu City', 'Litchfield Park', 'Marana', 'Maricopa',
    'Mesa', 'Nogales', 'Oro Valley', 'Page', 'Parker',
    'Payson', 'Peoria', 'Phoenix', 'Prescott', 'Prescott Valley',
    'Queen Creek', 'Safford', 'Sahuarita', 'San Luis', 'Scottsdale',
    'Sedona', 'Show Low', 'Sierra Vista', 'Somerton', 'Surprise',
    'Tempe', 'Tolleson', 'Tucson', 'Wickenburg', 'Willcox',
    'Williams', 'Winslow', 'Yuma',
  ],
  'Arkansas': [
    'Arkadelphia', 'Batesville', 'Beebe', 'Bella Vista', 'Benton',
    'Bentonville', 'Blytheville', 'Bryant', 'Cabot', 'Camden',
    'Centerton', 'Clarksville', 'Conway', 'Crossett', 'Dardanelle',
    'De Queen', 'Dumas', 'El Dorado', 'Fayetteville', 'Forrest City',
    'Fort Smith', 'Greenwood', 'Harrison', 'Heber Springs', 'Helena',
    'Hope', 'Hot Springs', 'Jacksonville', 'Jonesboro', 'Little Rock',
    'Lowell', 'Magnolia', 'Malvern', 'Marion', 'Maumelle',
    'Mena', 'Monticello', 'Morrilton', 'Mountain Home', 'Newport',
    'North Little Rock', 'Osceola', 'Paragould', 'Pine Bluff', 'Pocahontas',
    'Rogers', 'Russellville', 'Searcy', 'Sherwood', 'Siloam Springs',
    'Springdale', 'Stuttgart', 'Texarkana', 'Trumann', 'Van Buren',
    'Walnut Ridge', 'Warren', 'West Helena', 'West Memphis', 'Wynne',
  ],
  'California': [
    'Alameda', 'Alhambra', 'Anaheim', 'Antioch', 'Apple Valley',
    'Arcadia', 'Bakersfield', 'Baldwin Park', 'Bell', 'Bellflower',
    'Berkeley', 'Beverly Hills', 'Brea', 'Burbank', 'Camarillo',
    'Carson', 'Chico', 'Chino', 'Chino Hills', 'Chula Vista',
    'Citrus Heights', 'Clovis', 'Compton', 'Concord', 'Corona',
    'Costa Mesa', 'Daly City', 'Davis', 'Downey', 'El Cajon',
    'El Monte', 'Elk Grove', 'Escondido', 'Fairfield', 'Folsom',
    'Fontana', 'Fremont', 'Fresno', 'Fullerton', 'Garden Grove',
    'Glendale', 'Hawthorne', 'Hayward', 'Hemet', 'Hesperia',
    'Huntington Beach', 'Indio', 'Inglewood', 'Irvine', 'Jurupa Valley',
    'Lakewood', 'Lancaster', 'Livermore', 'Lodi', 'Long Beach',
    'Los Angeles', 'Lynwood', 'Manteca', 'Merced', 'Milpitas',
    'Modesto', 'Moreno Valley', 'Murrieta', 'Napa', 'Newport Beach',
    'Norwalk', 'Oakland', 'Oceanside', 'Ontario', 'Orange',
    'Oxnard', 'Palm Desert', 'Palm Springs', 'Palmdale', 'Palo Alto',
    'Pasadena', 'Petaluma', 'Pomona', 'Rancho Cucamonga', 'Redding',
    'Redlands', 'Redondo Beach', 'Rialto', 'Richmond', 'Riverside',
    'Roseville', 'Sacramento', 'Salinas', 'San Bernardino', 'San Diego',
    'San Francisco', 'San Jose', 'San Leandro', 'San Marcos', 'San Mateo',
    'San Ramon', 'Santa Ana', 'Santa Barbara', 'Santa Clara', 'Santa Clarita',
    'Santa Cruz', 'Santa Maria', 'Santa Monica', 'Santa Rosa', 'Simi Valley',
    'South Gate', 'Stockton', 'Sunnyvale', 'Temecula', 'Thousand Oaks',
    'Torrance', 'Tracy', 'Tulare', 'Turlock', 'Tustin',
    'Vacaville', 'Vallejo', 'Ventura', 'Victorville', 'Visalia',
    'Vista', 'Walnut Creek', 'West Covina', 'Westminster', 'Whittier',
  ],
  'Colorado': [
    'Alamosa', 'Arvada', 'Aspen', 'Aurora', 'Boulder',
    'Brighton', 'Broomfield', 'Canon City', 'Castle Rock', 'Centennial',
    'Colorado Springs', 'Commerce City', 'Delta', 'Denver', 'Durango',
    'Englewood', 'Evans', 'Fort Collins', 'Fort Morgan', 'Fountain',
    'Glenwood Springs', 'Grand Junction', 'Greeley', 'Highlands Ranch',
    'Lakewood', 'Littleton', 'Longmont', 'Louisville', 'Loveland',
    'Montrose', 'Northglenn', 'Pueblo', 'Steamboat Springs',
    'Sterling', 'Thornton', 'Westminster', 'Wheat Ridge',
  ],
  'Connecticut': [
    'Ansonia', 'Bloomfield', 'Branford', 'Bridgeport', 'Bristol',
    'Cheshire', 'Danbury', 'Darien', 'East Hartford', 'East Haven',
    'Enfield', 'Fairfield', 'Greenwich', 'Groton', 'Hamden',
    'Hartford', 'Manchester', 'Meriden', 'Middletown', 'Milford',
    'Naugatuck', 'New Britain', 'New Haven', 'New London', 'New Milford',
    'Newington', 'Norwalk', 'Norwich', 'Shelton', 'Simsbury',
    'South Windsor', 'Southington', 'Stamford', 'Stratford', 'Torrington',
    'Trumbull', 'Vernon', 'Wallingford', 'Waterbury', 'West Hartford',
    'West Haven', 'Westport', 'Wethersfield', 'Windham', 'Windsor',
  ],
  'Delaware': [
    'Bear', 'Brookside', 'Camden', 'Dover', 'Edgemoor',
    'Elsmere', 'Georgetown', 'Glasgow', 'Harrington', 'Middletown',
    'Milford', 'Millsboro', 'Newark', 'Pike Creek', 'Seaford',
    'Smyrna', 'Wilmington',
  ],
  'Florida': [
    'Altamonte Springs', 'Apopka', 'Aventura', 'Boca Raton', 'Boynton Beach',
    'Bradenton', 'Cape Coral', 'Clearwater', 'Coconut Creek', 'Coral Springs',
    'Daytona Beach', 'Deerfield Beach', 'Deland', 'Delray Beach', 'Deltona',
    'Dunedin', 'Fort Lauderdale', 'Fort Myers', 'Fort Pierce', 'Gainesville',
    'Hallandale Beach', 'Hialeah', 'Hollywood', 'Homestead', 'Jacksonville',
    'Jupiter', 'Kissimmee', 'Lake Worth', 'Lakeland', 'Lauderhill',
    'Margate', 'Melbourne', 'Miami', 'Miami Beach', 'Miami Gardens',
    'Miramar', 'Naples', 'North Miami', 'North Miami Beach', 'Ocala',
    'Orlando', 'Ormond Beach', 'Palm Bay', 'Palm Beach Gardens', 'Panama City',
    'Pembroke Pines', 'Pensacola', 'Plantation', 'Pompano Beach', 'Port Orange',
    'Port St. Lucie', 'Riviera Beach', 'Sarasota', 'St. Cloud', 'St. Petersburg',
    'Sunrise', 'Tallahassee', 'Tampa', 'Tamarac', 'West Palm Beach',
    'Weston', 'Winter Haven',
  ],
  'Georgia': [
    'Albany', 'Alpharetta', 'Athens', 'Atlanta', 'Augusta',
    'Brookhaven', 'Brunswick', 'Canton', 'Carrollton', 'Columbus',
    'Dalton', 'Douglasville', 'Dunwoody', 'East Point', 'Gainesville',
    'Griffin', 'Johns Creek', 'Kennesaw', 'LaGrange', 'Lawrenceville',
    'Macon', 'Marietta', 'Milledgeville', 'Milton', 'Newnan',
    'Peachtree City', 'Pooler', 'Rome', 'Roswell', 'Sandy Springs',
    'Savannah', 'Smyrna', 'Statesboro', 'Stockbridge', 'Valdosta',
    'Warner Robins',
  ],
  'Hawaii': [
    'East Honolulu', 'Hilo', 'Honolulu', 'Kahului', 'Kailua',
    'Kailua-Kona', 'Kaneohe', 'Kapolei', 'Kihei', 'Lihue',
    'Mililani Town', 'Pearl City', 'Wahiawa', 'Waipahu',
  ],
  'Idaho': [
    'Ammon', 'Blackfoot', 'Boise', 'Burley', 'Caldwell',
    'Chubbuck', "Coeur d'Alene", 'Eagle', 'Idaho Falls', 'Jerome',
    'Kuna', 'Lewiston', 'Meridian', 'Moscow', 'Mountain Home',
    'Nampa', 'Pocatello', 'Post Falls', 'Rexburg', 'Sandpoint',
    'Twin Falls',
  ],
  'Illinois': [
    'Arlington Heights', 'Aurora', 'Bartlett', 'Belleville', 'Berwyn',
    'Bloomington', 'Bolingbrook', 'Buffalo Grove', 'Carol Stream', 'Champaign',
    'Chicago', 'Cicero', 'Crystal Lake', 'Decatur', 'DeKalb',
    'Des Plaines', 'Downers Grove', 'East St. Louis', 'Elgin', 'Elmhurst',
    'Evanston', 'Joliet', 'Lombard', 'Moline', 'Mount Prospect',
    'Naperville', 'Normal', 'North Chicago', 'Oak Lawn', 'Oak Park',
    'Orland Park', 'Palatine', 'Peoria', 'Plainfield', 'Quincy',
    'Rockford', 'Round Lake Beach', 'Schaumburg', 'Skokie', 'Springfield',
    'St. Charles', 'Tinley Park', 'Urbana', 'Waukegan', 'Wheaton',
  ],
  'Indiana': [
    'Anderson', 'Bloomington', 'Carmel', 'Columbus', 'Elkhart',
    'Evansville', 'Fishers', 'Fort Wayne', 'Gary', 'Greenwood',
    'Hammond', 'Indianapolis', 'Jeffersonville', 'Kokomo', 'Lafayette',
    'Lawrence', 'Michigan City', 'Mishawaka', 'Muncie', 'New Albany',
    'Noblesville', 'Richmond', 'South Bend', 'Terre Haute', 'Westfield',
  ],
  'Iowa': [
    'Ames', 'Ankeny', 'Bettendorf', 'Burlington', 'Cedar Falls',
    'Cedar Rapids', 'Clinton', 'Council Bluffs', 'Davenport', 'Des Moines',
    'Dubuque', 'Iowa City', 'Marion', 'Marshalltown', 'Mason City',
    'Sioux City', 'Urbandale', 'Waukee', 'Waterloo', 'West Des Moines',
  ],
  'Kansas': [
    'Dodge City', 'Garden City', 'Hutchinson', 'Junction City', 'Kansas City',
    'Lawrence', 'Leavenworth', 'Leawood', 'Lenexa', 'Manhattan',
    'Olathe', 'Overland Park', 'Salina', 'Shawnee', 'Topeka',
    'Wichita',
  ],
  'Kentucky': [
    'Ashland', 'Bowling Green', 'Covington', 'Elizabethtown',
    'Florence', 'Frankfort', 'Georgetown', 'Henderson', 'Hopkinsville',
    'Jeffersontown', 'Lexington', 'Louisville', 'Nicholasville',
    'Owensboro', 'Paducah', 'Radcliff', 'Richmond',
  ],
  'Louisiana': [
    'Alexandria', 'Baton Rouge', 'Bossier City', 'Central', 'Hammond',
    'Houma', 'Kenner', 'Lafayette', 'Lake Charles', 'Mandeville',
    'Metairie', 'Monroe', 'Morgan City', 'Natchitoches', 'New Iberia',
    'New Orleans', 'Ruston', 'Shreveport', 'Slidell', 'Sulphur',
    'Thibodaux',
  ],
  'Maine': [
    'Auburn', 'Augusta', 'Bangor', 'Bath', 'Biddeford',
    'Brewer', 'Brunswick', 'Gorham', 'Lewiston', 'Portland',
    'Saco', 'Sanford', 'South Portland', 'Waterville', 'Westbrook',
  ],
  'Maryland': [
    'Annapolis', 'Baltimore', 'Bel Air', 'Bethesda', 'Bowie',
    'College Park', 'Columbia', 'Cumberland', 'Frederick', 'Gaithersburg',
    'Germantown', 'Hagerstown', 'Laurel', 'Rockville', 'Salisbury',
    'Silver Spring', 'Waldorf',
  ],
  'Massachusetts': [
    'Attleboro', 'Barnstable', 'Boston', 'Brockton', 'Cambridge',
    'Chicopee', 'Everett', 'Fall River', 'Fitchburg', 'Framingham',
    'Haverhill', 'Holyoke', 'Lawrence', 'Leominster', 'Lowell',
    'Lynn', 'Malden', 'Medford', 'New Bedford', 'Newton',
    'Peabody', 'Pittsfield', 'Plymouth', 'Quincy', 'Revere',
    'Salem', 'Somerville', 'Springfield', 'Taunton', 'Waltham',
    'Watertown', 'Worcester',
  ],
  'Michigan': [
    'Ann Arbor', 'Battle Creek', 'Bay City', 'Dearborn', 'Dearborn Heights',
    'Detroit', 'East Lansing', 'Flint', 'Grand Rapids', 'Holland',
    'Kalamazoo', 'Kentwood', 'Lansing', 'Lincoln Park', 'Livonia',
    'Midland', 'Mount Pleasant', 'Muskegon', 'Pontiac', 'Port Huron',
    'Rochester Hills', 'Roseville', 'Royal Oak', 'Saginaw', 'Southfield',
    'St. Clair Shores', 'Sterling Heights', 'Taylor', 'Traverse City',
    'Troy', 'Warren', 'Westland', 'Wyoming',
  ],
  'Minnesota': [
    'Apple Valley', 'Blaine', 'Bloomington', 'Brooklyn Park', 'Burnsville',
    'Coon Rapids', 'Duluth', 'Eagan', 'Eden Prairie', 'Edina',
    'Lakeville', 'Mankato', 'Maple Grove', 'Minneapolis', 'Minnetonka',
    'Moorhead', 'Plymouth', 'Rochester', 'St. Cloud', 'St. Paul',
    'Woodbury',
  ],
  'Mississippi': [
    'Biloxi', 'Brandon', 'Clinton', 'Columbus', 'Gautier',
    'Gulfport', 'Hattiesburg', 'Horn Lake', 'Jackson', 'Meridian',
    'Moss Point', 'Natchez', 'Olive Branch', 'Oxford', 'Pearl',
    'Ridgeland', 'Southaven', 'Starkville', 'Tupelo', 'Vicksburg',
  ],
  'Missouri': [
    'Blue Springs', 'Cape Girardeau', 'Columbia', 'Florissant',
    'Independence', 'Jefferson City', 'Joplin', 'Kansas City',
    "Lee's Summit", 'Liberty', "O'Fallon", 'Raytown', 'Springfield',
    'St. Charles', 'St. Joseph', 'St. Louis', 'St. Peters',
    'University City',
  ],
  'Montana': [
    'Billings', 'Bozeman', 'Butte', 'Great Falls', 'Helena',
    'Kalispell', 'Missoula',
  ],
  'Nebraska': [
    'Bellevue', 'Columbus', 'Fremont', 'Grand Island', 'Hastings',
    'Kearney', 'Lincoln', 'Norfolk', 'North Platte', 'Omaha',
    'Papillion',
  ],
  'Nevada': [
    'Carson City', 'Enterprise', 'Henderson', 'Las Vegas', 'North Las Vegas',
    'Paradise', 'Reno', 'Sparks', 'Spring Valley', 'Sunrise Manor',
    'Whitney',
  ],
  'New Hampshire': [
    'Berlin', 'Claremont', 'Concord', 'Dover', 'Keene',
    'Laconia', 'Lebanon', 'Manchester', 'Nashua', 'Portsmouth',
    'Rochester', 'Somersworth',
  ],
  'New Jersey': [
    'Atlantic City', 'Bayonne', 'Camden', 'Cherry Hill', 'Clifton',
    'East Orange', 'Edison', 'Elizabeth', 'Hackensack', 'Hoboken',
    'Irvington', 'Jersey City', 'Lakewood', 'Newark', 'New Brunswick',
    'Parsippany', 'Passaic', 'Paterson', 'Perth Amboy', 'Plainfield',
    'Toms River', 'Trenton', 'Union City', 'Vineland', 'Wayne',
    'Woodbridge',
  ],
  'New Mexico': [
    'Alamogordo', 'Albuquerque', 'Carlsbad', 'Clovis', 'Farmington',
    'Gallup', 'Hobbs', 'Las Cruces', 'Las Vegas', 'Los Alamos',
    'Portales', 'Rio Rancho', 'Roswell', 'Ruidoso', 'Santa Fe',
    'Silver City', 'Sunland Park',
  ],
  'New York': [
    'Albany', 'Amherst', 'Binghamton', 'Brighton', 'Bronx',
    'Brooklyn', 'Buffalo', 'Cheektowaga', 'Clay', 'Elmira',
    'Greece', 'Hempstead', 'Islip', 'Ithaca', 'Manhattan',
    'Mount Vernon', 'New Rochelle', 'New York City', 'Niagara Falls',
    'North Hempstead', 'Oyster Bay', 'Poughkeepsie', 'Queens',
    'Rochester', 'Rome', 'Schenectady', 'Staten Island', 'Syracuse',
    'Tonawanda', 'Troy', 'Utica', 'White Plains', 'Yonkers',
  ],
  'North Carolina': [
    'Apex', 'Asheville', 'Burlington', 'Cary', 'Chapel Hill',
    'Charlotte', 'Concord', 'Durham', 'Fayetteville', 'Gastonia',
    'Goldsboro', 'Greensboro', 'Greenville', 'Hickory', 'High Point',
    'Huntersville', 'Jacksonville', 'Kannapolis', 'Morrisville',
    'New Bern', 'Raleigh', 'Rocky Mount', 'Salisbury', 'Wilmington',
    'Wilson', 'Winston-Salem',
  ],
  'North Dakota': [
    'Bismarck', 'Fargo', 'Grand Forks', 'Mandan', 'Minot',
    'West Fargo', 'Williston',
  ],
  'Ohio': [
    'Akron', 'Canton', 'Cincinnati', 'Cleveland', 'Columbus',
    'Dayton', 'Elyria', 'Fairfield', 'Hamilton', 'Kettering',
    'Lakewood', 'Lancaster', 'Lima', 'Lorain', 'Mansfield',
    'Mentor', 'Middletown', 'Newark', 'Parma', 'Springfield',
    'Strongsville', 'Toledo', 'Warren', 'Youngstown',
  ],
  'Oklahoma': [
    'Bartlesville', 'Bixby', 'Broken Arrow', 'Edmond', 'Enid',
    'Lawton', 'Midwest City', 'Moore', 'Muskogee', 'Norman',
    'Oklahoma City', 'Owasso', 'Shawnee', 'Stillwater', 'Tulsa',
  ],
  'Oregon': [
    'Albany', 'Aloha', 'Beaverton', 'Bend', 'Corvallis',
    'Eugene', 'Gresham', 'Hillsboro', 'Lake Oswego', 'Medford',
    'Portland', 'Redmond', 'Salem', 'Springfield', 'Tigard',
  ],
  'Pennsylvania': [
    'Allentown', 'Altoona', 'Bethlehem', 'Chester', 'Erie',
    'Harrisburg', 'Lancaster', 'Levittown', 'Philadelphia', 'Pittsburgh',
    'Reading', 'Scranton', 'Upper Darby', 'Wilkes-Barre', 'York',
  ],
  'Rhode Island': [
    'Central Falls', 'Cranston', 'East Providence', 'Newport',
    'North Providence', 'Pawtucket', 'Providence', 'Warwick', 'Woonsocket',
  ],
  'South Carolina': [
    'Aiken', 'Anderson', 'Bluffton', 'Charleston', 'Columbia',
    'Conway', 'Florence', 'Goose Creek', 'Greenville', 'Greer',
    'Hilton Head Island', 'Mount Pleasant', 'Myrtle Beach',
    'North Charleston', 'Rock Hill', 'Spartanburg', 'Summerville', 'Sumter',
  ],
  'South Dakota': [
    'Aberdeen', 'Brandon', 'Brookings', 'Mitchell', 'Pierre',
    'Rapid City', 'Sioux Falls', 'Watertown',
  ],
  'Tennessee': [
    'Bartlett', 'Brentwood', 'Chattanooga', 'Clarksville', 'Cleveland',
    'Collierville', 'Columbia', 'Franklin', 'Germantown', 'Hendersonville',
    'Jackson', 'Johnson City', 'Kingsport', 'Knoxville', 'Memphis',
    'Morristown', 'Murfreesboro', 'Nashville', 'Smyrna', 'Spring Hill',
  ],
  'Texas': [
    'Abilene', 'Allen', 'Amarillo', 'Arlington', 'Austin',
    'Baytown', 'Beaumont', 'Bedford', 'Brownsville', 'Bryan',
    'Carrollton', 'Cedar Park', 'Cleburne', 'College Station', 'Conroe',
    'Corpus Christi', 'Dallas', 'Denton', 'Edinburg', 'El Paso',
    'Euless', 'Flower Mound', 'Fort Worth', 'Frisco', 'Garland',
    'Georgetown', 'Grand Prairie', 'Grapevine', 'Harlingen', 'Houston',
    'Irving', 'Killeen', 'Laredo', 'League City', 'Lewisville',
    'Longview', 'Lubbock', 'Lufkin', 'McAllen', 'McKinney',
    'Mesquite', 'Midland', 'Mission', 'Missouri City', 'New Braunfels',
    'Odessa', 'Pasadena', 'Pearland', 'Pflugerville', 'Plano',
    'Port Arthur', 'Richardson', 'Round Rock', 'Rowlett', 'San Angelo',
    'San Antonio', 'San Marcos', 'Sugar Land', 'Temple', 'Texas City',
    'Tyler', 'Victoria', 'Waco', 'Wichita Falls', 'Wylie',
  ],
  'Utah': [
    'Bountiful', 'Cedar City', 'Clearfield', 'Draper', 'Herriman',
    'Highland', 'Layton', 'Lehi', 'Logan', 'Millcreek',
    'Murray', 'Ogden', 'Orem', 'Provo', 'Riverton',
    'Salt Lake City', 'Sandy', 'South Jordan', 'South Salt Lake',
    'Spanish Fork', 'Springville', 'St. George', 'Taylorsville',
    'Tooele', 'West Jordan', 'West Valley City',
  ],
  'Vermont': [
    'Barre', 'Burlington', 'Essex Junction', 'Montpelier', 'Rutland',
    'South Burlington', 'St. Albans',
  ],
  'Virginia': [
    'Alexandria', 'Blacksburg', 'Charlottesville', 'Chesapeake',
    'Danville', 'Hampton', 'Harrisonburg', 'Leesburg', 'Lynchburg',
    'Manassas', 'Newport News', 'Norfolk', 'Petersburg', 'Portsmouth',
    'Reston', 'Richmond', 'Roanoke', 'Springfield', 'Suffolk',
    'Virginia Beach',
  ],
  'Washington': [
    'Auburn', 'Bellevue', 'Bellingham', 'Bothell', 'Bremerton',
    'Burien', 'Everett', 'Federal Way', 'Kennewick', 'Kent',
    'Kirkland', 'Lakewood', 'Marysville', 'Pasco', 'Redmond',
    'Renton', 'Richland', 'Seattle', 'Shoreline', 'Spokane',
    'Spokane Valley', 'Tacoma', 'Vancouver', 'Yakima',
  ],
  'West Virginia': [
    'Beckley', 'Charleston', 'Clarksburg', 'Huntington', 'Martinsburg',
    'Morgantown', 'Parkersburg', 'Weirton', 'Wheeling',
  ],
  'Wisconsin': [
    'Appleton', 'Eau Claire', 'Green Bay', 'Janesville', 'Kenosha',
    'La Crosse', 'Madison', 'Milwaukee', 'Oshkosh', 'Racine',
    'Sheboygan', 'Waukesha', 'Wausau',
  ],
  'Wyoming': [
    'Casper', 'Cheyenne', 'Gillette', 'Green River', 'Laramie',
    'Rock Springs',
  ],
};
